### ISSUE TITLE
Extension seems to break Quarkus extension catalog publishing

### ISSUE THREAD

**Issue by mcollovati** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#182]
Recently, we published an updated version of our extension, but noticed the catalog was not updated with the latest version.
Looking at the quarkus-extension-catalog [Publish to the Extension Registry](https://github.com/quarkusio/quarkus-extension-catalog/actions/workflows/publish.yaml) jobs, we spot this error in the logs

```
2024-09-03T11:32:21.605804705Z[Etc/UTC] [INFO] ---------------------------------------------------------------
2024-09-03T11:32:21.605888161Z[Etc/UTC] [INFO] Processing extension ./extensions/quarkiverse-reactive-messaging-nats-jetstream.yaml
2024-09-03T11:32:21.605936220Z[Etc/UTC] [INFO] ---------------------------------------------------------------
Error: -03T11:32:21.614461210Z[Etc/UTC] [ERROR] Error while processing extension
java.io.FileNotFoundException: JAR entry META-INF/quarkus-extension.yaml not found in /tmp/jar_cache15376286140294748740.tmp
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:146)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at catalog_publish.readExtension(catalog_publish.java:323)
	at catalog_publish.processExtension(catalog_publish.java:254)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at catalog_publish.list(catalog_publish.java:105)
	at catalog_publish.call(catalog_publish.java:91)
	at catalog_publish.call(catalog_publish.java:54)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at catalog_publish.main(catalog_publish.java:79)
```

It looks like this extension has a maven relocation for several packages, so I wonder if the [Quarkus catalog entry](//github.com/quarkusio/quarkus-extension-catalog/blob/main/extensions/quarkiverse-reactive-messaging-nats-jetstream.yaml) should be updated with the new maven coordinate.
Maybe this could fix the publishing issues.

**Comment by ozangunalp** [comment]
I did not expect that, given there is a maven relocation in place. 
Let me propose the change for that entry.

**Comment by mcollovati** [comment]
Thanks for quick answer!
Mine is just a guess. I hope that updating the coordinates will not be a breaking change.
I'm pretty sure the maintainers of quarkus-extension-catalog can provide some good advice.

**Comment by mcollovati** [comment]
Quarkus catalog publishing is working now. I think this issue can be closed.
Thanks for support
